# Generated by Django 5.1.5 on 2025-02-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="EncodedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encoded_image", models.ImageField(upload_to="encoded_images/")),
                ("secret_data", models.TextField()),
                (
                    "original_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Steg_app.uploadedimage",
                    ),
                ),
            ],
        ),
    ]
