# Generated by Django 5.1.5 on 2025-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Untitled Message", max_length=255)),
                ("encrypted_aes_key", models.BinaryField()),
                ("cipher_text", models.BinaryField()),
                ("nonce", models.BinaryField()),
                ("tag", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
