# Generated by Django 5.1.5 on 2025-02-19 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0006_encryptedmessage_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedmessage",
            name="userid",
        ),
    ]
