# Generated by Django 5.1.5 on 2025-02-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0007_remove_encryptedmessage_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedmessage",
            name="userid",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="Steg_app.userregistration",
            ),
        ),
    ]
