# Generated by Django 5.1.5 on 2025-02-27 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0008_encryptedmessage_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="watermark_logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="watermark_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default="bottom-right",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="watermark_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="watermarked_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="watermarked_images/"
            ),
        ),
    ]
