# Generated by Django 5.1.5 on 2025-03-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0009_uploadedimage_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="watermarkKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_aes_key", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Steg_app.userregistration",
                    ),
                ),
            ],
        ),
    ]
