# Generated by Django 5.1.5 on 2025-03-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0010_watermarkkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watermarkkey",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Steg_app.uploadedimage"
            ),
        ),
    ]
