# Generated by Django 5.1.5 on 2025-03-02 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0011_alter_watermarkkey_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watermarkkey",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watermark_key",
                to="Steg_app.uploadedimage",
            ),
        ),
    ]
