# Generated by Django 5.1.5 on 2025-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0012_alter_watermarkkey_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="watermarkkey",
            name="iv",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
    ]
