# Generated by Django 5.1.5 on 2025-03-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0014_alter_uploadedimage_watermark_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="watermark_position",
            field=models.CharField(default="None", max_length=20),
        ),
    ]
