# Generated by Django 5.1.5 on 2025-03-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0015_alter_uploadedimage_watermark_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="watermark_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default="bottom-right",
                max_length=20,
            ),
        ),
    ]
