# Generated by Django 5.1.5 on 2025-03-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0017_alter_uploadedimage_watermark_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistration",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics/"
            ),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="purpose",
            field=models.TextField(blank=True, null=True),
        ),
    ]
