# Generated by Django 5.1.5 on 2025-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0018_userregistration_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encodedimage",
            name="encoded_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="original_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="watermarkkey",
            name="watermarked_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
