# Generated by Django 5.1.5 on 2025-03-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0019_encodedimage_encoded_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TamperingDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tampering_check_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("watermarked", "Watermarked"),
                            ("steganographed", "Steganographed"),
                        ],
                        default="Not Verified",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tampeing_checks",
                        to="Steg_app.uploadedimage",
                    ),
                ),
            ],
        ),
    ]
