# Generated by Django 5.1.5 on 2025-03-24 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0020_tamperingdetection"),
    ]

    operations = [
        migrations.AddField(
            model_name="tamperingdetection",
            name="encoded_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Steg_app.encodedimage",
            ),
        ),
        migrations.AlterField(
            model_name="tamperingdetection",
            name="status",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("watermarked", "Watermarked"),
                    ("steganographed", "Steganographed"),
                ],
                default="Not Verified",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tamperingdetection",
            name="uploaded_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Steg_app.uploadedimage",
            ),
        ),
    ]
