# Generated by Django 5.1.5 on 2025-03-25 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0022_alter_encodedimage_encoded_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserloginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Steg_app.userregistration",
                    ),
                ),
            ],
        ),
    ]
