# Generated by Django 5.1.5 on 2025-03-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0023_userloginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userloginhistory",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userloginhistory",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("SUCCESS", "Successfull Login"), ("Failed", "Failed Login")],
                max_length=20,
                null=True,
            ),
        ),
    ]
