# Generated by Django 5.1.5 on 2025-04-11 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Steg_app", "0027_uploadedimage_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
